spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
        # search-locations: "classpath:/config"
        git:
          uri: "https://github.com/santhoshshetty/softbank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8071